spring.application.name=config-service

server.port=8888

# Location of your Git config repository
spring.cloud.config.server.git.uri=https://github.com/table2table-org/table2table-config.git

# (Optional) Default branch
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=DEV

# EUREKA
#use this if need local deployment
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka